# THIS FILE IS DEPRECATED; MOVING TO POSTMAN COLLECTION RUNS
# It's still useful to play around within VSCode during development

@baseUrl = http://localhost:3001
@defaultEmail = test@test.com
@defaultPassword = testtest1234


GET {{baseUrl}}

###

POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "email": "{{defaultEmail}}",
  "password": "{{defaultPassword}}"
}

###

# @name auth
@authToken = {{ auth.response.headers.X-AuthToken }}
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "{{defaultEmail}}",
  "password": "{{defaultPassword}}"
}

###

GET {{baseUrl}}/user
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/user/username
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/user/username/availability
Content-Type: application/json
Authorization: Bearer {{authToken}}

{ "username": "MyUsername2" }

###

PATCH {{baseUrl}}/user/username
Content-Type: application/json
Authorization: Bearer {{authToken}}

{ "username": "MyUsername2" }

###

GET {{baseUrl}}/user/profile
Authorization: Bearer {{authToken}}

###

GET {{baseUrl}}/user/profile/name
Authorization: Bearer {{authToken}}

###

PUT {{baseUrl}}/user/profile/name
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "value": "John Doe"
}

###

PUT {{baseUrl}}/user/profile/phone
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "value": "+18004444444"
}

###
GET {{baseUrl}}/user/settings
Authorization: Bearer {{authToken}}

###

GET {{baseUrl}}/user/settings/subscribeToNewsletter
Authorization: Bearer {{authToken}}

###

PUT {{baseUrl}}/user/settings/subscribeToNewsletter/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "value": false
}

###

PATCH {{baseUrl}}/user/password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "currentPassword": "{{defaultPassword}}",
  "newPassword": "testtest2",
  "confirmPassword": "testtest2"
}

###

GET {{baseUrl}}/user/client-settings
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

PUT {{baseUrl}}/user/client-settings
Content-Type: application/json
Authorization: Bearer {{authToken}}

//{}
{ "one": 2, "two": 3, "foo": "bar", "bar": "baz" }

###

GET {{baseUrl}}/jokes?type=programming&amount=5

###

GET {{baseUrl}}/example/add/4/232

###

GET {{baseUrl}}/example/test-error

###

GET {{baseUrl}}/blog
Authorization: Bearer {{authToken}}

###

POST {{baseUrl}}/blog
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Hey there!",
  "content": "This is a blog post!"
}