language: node_js
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

env:
  - DB_URI="mongodb+srv://helio:Cs6Uqm8bDcNg6rzP@cluster0-6jx5i.mongodb.net/dev?retryWrites=true"
  - JWT_SECRET="supersecret!"
  - CONSOLE_LOG=false
  - CONSOLE_ERRORS=false